// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BgProcessInfo is the JSON shape the frontend expects from `shell_bg_list`.
 */
export interface BgProcessInfo {
    "handle": number;
    "command": string;
    "cwd": string;
    "started_at_ms": number;
    "exited": boolean;
    "exit_code": number | null;
}
