// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AiHttpRequestArgs is a non-streaming HTTP call.
 */
export interface AiHttpRequestArgs {
    "url": string;
    "method": string;
    "headers": { [_ in string]?: string } | null;
    "body": string | null;
    "allowPrivateNetwork": boolean;
}

/**
 * AiHttpStreamArgs is the request body for `ai_http_stream`.
 */
export interface AiHttpStreamArgs {
    "url": string;
    "method": string;
    "headers": { [_ in string]?: string } | null;
    "body": string | null;
    "allowPrivateNetwork": boolean;
    "onEventEvent": string;
}

/**
 * DirEntry mirrors `DirEntry` in `src/modules/explorer/lib/useFileTree.ts`.
 */
export interface DirEntry {
    "name": string;

    /**
     * "file" | "dir" | "symlink"
     */
    "kind": string;
    "size": number;
    "mtime": number;
    "gitignored": boolean;
}

/**
 * FsCopyArgs copies one or more files/dirs into a destination directory.
 * Mirrors the Rust backend's `fs_copy(sources, dest_dir)` signature so
 * the frontend drag-drop payload ({sources, destDir}) flows through
 * unchanged.
 */
export interface FsCopyArgs {
    "sources": string[] | null;
    "destDir": string;
    "workspace": WorkspaceEnv;
}

/**
 * FsCreateArgs creates a file or directory.
 */
export interface FsCreateArgs {
    "path": string;
    "workspace": WorkspaceEnv;
}

/**
 * FsDeleteArgs deletes a file/dir.
 */
export interface FsDeleteArgs {
    "path": string;
    "workspace": WorkspaceEnv;
}

/**
 * FsGlobArgs matches glob patterns.
 */
export interface FsGlobArgs {
    "pattern": string;
    "root": string;
    "maxResults"?: number;
    "workspace": WorkspaceEnv;
}

/**
 * FsGlobHit mirrors a single glob match.
 */
export interface FsGlobHit {
    "path": string;
    "rel": string;
}

/**
 * FsGlobResponse mirrors the Rust `GlobResponse` envelope.
 */
export interface FsGlobResponse {
    "hits": FsGlobHit[] | null;
    "truncated": boolean;
}

/**
 * FsGrepArgs runs a content search (ripgrep equivalent).
 */
export interface FsGrepArgs {
    "root": string;
    "pattern": string;
    "glob"?: string[] | null;
    "caseInsensitive": boolean;
    "maxResults": number;
    "workspace": WorkspaceEnv;
}

/**
 * FsGrepHit mirrors a single grep hit. Field names mirror the Rust
 * backend's serialised struct (path, rel, line, text).
 */
export interface FsGrepHit {
    "path": string;
    "rel": string;
    "line": number;
    "text": string;
}

/**
 * FsGrepResponse mirrors the Rust `GrepResponse` envelope.
 */
export interface FsGrepResponse {
    "hits": FsGrepHit[] | null;
    "truncated": boolean;
    "files_scanned": number;
}

/**
 * FsListFilesArgs returns files matching a glob.
 */
export interface FsListFilesArgs {
    "pattern": string;
    "root": string;
    "limit"?: number;
    "workspace": WorkspaceEnv;
}

/**
 * FsListFilesResult mirrors the Rust `ListFilesResult` envelope.
 */
export interface FsListFilesResult {
    "files": string[] | null;
    "truncated": boolean;
}

/**
 * FsReadDirArgs lists entries of a directory.
 */
export interface FsReadDirArgs {
    "path": string;
    "showHidden": boolean;
    "gitDecorations": boolean;
    "workspace": WorkspaceEnv;
}

/**
 * FsRenameArgs renames/moves a path.
 */
export interface FsRenameArgs {
    "from": string;
    "to": string;
    "workspace": WorkspaceEnv;
}

/**
 * FsSearchArgs searches for files by glob/name.
 */
export interface FsSearchArgs {
    "query": string;
    "root": string;
    "limit": number;
    "showHidden": boolean;
    "workspace": WorkspaceEnv;
}

/**
 * FsSearchHit is one entry from the explorer search bar.
 */
export interface FsSearchHit {
    "path": string;
    "rel": string;
    "name": string;
    "is_dir": boolean;
}

/**
 * FsSearchResponse mirrors the Rust explorer search envelope.
 */
export interface FsSearchResponse {
    "hits": FsSearchHit[] | null;
    "truncated": boolean;
}

/**
 * FsStat mirrors `fs_stat`. `Kind` is "file" | "dir" | "symlink"
 * matching the Rust `StatKind` enum (serde rename_all = "lowercase").
 * The frontend reads `kind` directly to pick an icon.
 */
export interface FsStat {
    "size": number;
    "mtime": number;
    "kind": string;
}

/**
 * FsWatchArgs adds/removes a directory from the watcher.
 */
export interface FsWatchArgs {
    "paths": string[] | null;
    "workspace": WorkspaceEnv;
}

/**
 * FsWriteArgs writes text content to a file.
 */
export interface FsWriteArgs {
    "path": string;
    "content": string;
    "workspace": WorkspaceEnv;
}

/**
 * GitBranchEntry mirrors one row of the Rust backend's branch list.
 */
export interface GitBranchEntry {
    "name": string;

    /**
     * "local" | "worktree"
     */
    "kind": string;
    "worktreePath": string | null;
    "isHead": boolean;
    "isDetached": boolean;
}

/**
 * GitBranchListResult mirrors the envelope for `git_list_branches`.
 */
export interface GitBranchListResult {
    "branches": GitBranchEntry[] | null;
}

/**
 * GitChangedFile mirrors the Rust backend's `GitChangedFile` — one row of
 * the status view.
 */
export interface GitChangedFile {
    "path": string;
    "originalPath": string | null;
    "indexStatus": string;
    "worktreeStatus": string;
    "staged": boolean;
    "unstaged": boolean;
    "untracked": boolean;
    "statusLabel": string;
}

/**
 * GitCommitFileChange mirrors one row of the Rust backend's
 * `git_commit_files` list.
 */
export interface GitCommitFileChange {
    "path": string;
    "originalPath": string | null;
    "status": string;
    "statusLabel": string;
    "added": number;
    "removed": number;
    "isBinary": boolean;
}

/**
 * GitCommitResult mirrors `git_commit` return shape.
 */
export interface GitCommitResult {
    "commitSha": string;
    "summary": string;
}

/**
 * GitDiffContentResult is the side-by-side blob content diff for
 * `git_diff_content` / `git_commit_file_diff`.
 */
export interface GitDiffContentResult {
    "originalContent": string;
    "modifiedContent": string;
    "isBinary": boolean;
    "fallbackPatch": string;
    "truncated": boolean;
}

/**
 * GitDiffResult is the unified diff output for `git_diff` / `git_show_commit`.
 */
export interface GitDiffResult {
    "diffText": string;
    "truncated": boolean;
}

/**
 * GitDiscardEntry is one entry in `git_discard`'s request payload.
 */
export interface GitDiscardEntry {
    "path": string;
    "untracked": boolean;
}

/**
 * GitLogEntry mirrors a single row of the Rust backend's `git_log`.
 */
export interface GitLogEntry {
    "sha": string;
    "shortSha": string;
    "author": string;
    "authorEmail": string;
    "timestampSecs": number;
    "parents": string[] | null;
    "subject": string;
    "filesChanged": number;
    "insertions": number;
    "deletions": number;
}

/**
 * GitPanelSnapshot mirrors the Rust backend's `GitPanelSnapshot`.
 * `Repo` and `Status` may be nil when cwd isn't in a repo.
 */
export interface GitPanelSnapshot {
    "repo": GitRepoInfo | null;
    "status": GitStatusSnapshot | null;
}

/**
 * GitPushResult mirrors `git_push` return shape.
 */
export interface GitPushResult {
    "remote": string | null;
    "branch": string | null;
    "pushed": boolean;
}

/**
 * GitRepoInfo mirrors the Rust backend's `GitRepoInfo`. Returned by
 * `git_resolve_repo` (nullable when cwd isn't inside a repo).
 */
export interface GitRepoInfo {
    "repoRoot": string;
    "branch": string;
    "upstream": string | null;
    "isDetached": boolean;
}

/**
 * GitStatusSnapshot mirrors the Rust backend's `GitStatusSnapshot`. Returned
 * by `git_status`.
 */
export interface GitStatusSnapshot {
    "repoRoot": string;
    "branch": string;
    "upstream": string | null;
    "ahead": number;
    "behind": number;
    "isDetached": boolean;
    "truncated": boolean;
    "changedFiles": GitChangedFile[] | null;
}

/**
 * HistoryListArgs lists recorded commands.
 */
export interface HistoryListArgs {
    "query"?: string;
    "limit": number;
}

/**
 * HistoryRecordArgs records a command in history.
 */
export interface HistoryRecordArgs {
    "command": string;
}

/**
 * HistorySuggestArgs provides fuzzy history suggestions.
 */
export interface HistorySuggestArgs {
    "line": string;
    "limit": number;
}

/**
 * LmPingArgs pings a local model endpoint.
 */
export interface LmPingArgs {
    "baseUrl": string;
}

/**
 * LspSpawnArgs is the request body for `lsp_spawn`. The two trailing fields
 * carry Channel attachment IDs produced by the frontend's SPECIAL handler
 * in `wails-shim/core.ts` (which renames `onMessage` -> `onMessageEvent` and
 * `onExit` -> `onExitEvent` before crossing the bridge).
 */
export interface LspSpawnArgs {
    "command": string;
    "args": string[] | null;
    "env": { [_ in string]?: string } | null;
    "root": string;
    "maxRssMb": number | null;
    "workspace": WorkspaceEnv;
    "onMessageEvent": string;
    "onExitEvent": string;
}

/**
 * PtyOpenArgs is the request body for `PtyOpen`. Simple-shell-style: the
 * backend emits `pty:<id>` and `pty:exit:<id>` events on the Wails event
 * bus, and the frontend subscribes to those names directly. No Channel
 * attachment IDs are needed.
 */
export interface PtyOpenArgs {
    "cols": number;
    "rows": number;
    "cwd": string | null;
    "workspace": WorkspaceEnv;
    "shell": string | null;
}

/**
 * ReadResult mirrors `ReadResult` in `src/modules/ai/lib/native.ts`.
 * The frontend uses `kind` to decide whether to surface content, refuse
 * binary blobs, or warn about oversized files.
 */
export interface ReadResult {
    /**
     * "text" | "binary" | "toolarge"
     */
    "kind": string;
    "content"?: string;
    "size": number;
    "limit"?: number;
}

/**
 * ShellBgKillArgs kills a running background job.
 */
export interface ShellBgKillArgs {
    "handle": number;
}

/**
 * ShellBgLogsArgs fetches captured logs.
 */
export interface ShellBgLogsArgs {
    "handle": number;
    "sinceOffset": number;
}

/**
 * ShellBgSpawnArgs starts a background process.
 */
export interface ShellBgSpawnArgs {
    "command": string;
    "cwd": string;
    "workspace": WorkspaceEnv;
}

/**
 * ShellRunArgs runs a one-shot shell command.
 */
export interface ShellRunArgs {
    "command": string;
    "cwd": string;
    "timeoutSecs": number;
    "workspace": WorkspaceEnv;
}

/**
 * ShellSessionOpenArgs starts an interactive shell session.
 */
export interface ShellSessionOpenArgs {
    "cwd": string;
    "workspace": WorkspaceEnv;
    "shell"?: string;
}

/**
 * ShellSessionResult mirrors the envelope the frontend expects from
 * `shell_session_run`: stdout, stderr, exit code, cwd after the command,
 * and timeout/truncation flags.
 */
export interface ShellSessionResult {
    "stdout": string;
    "stderr": string;
    "exit_code": number | null;
    "timed_out": boolean;
    "truncated": boolean;
    "cwd_after": string;
}

/**
 * ShellSessionRunArgs sends a command to an existing session.
 */
export interface ShellSessionRunArgs {
    "id": number;
    "command": string;
    "cwd": string;
    "timeoutSecs": number;
}

/**
 * StoreLoadArgs loads a JSON KV bag.
 */
export interface StoreLoadArgs {
    "path": string;
}

/**
 * StoreSaveArgs persists a JSON KV bag.
 */
export interface StoreSaveArgs {
    "path": string;
    "data": { [_ in string]?: any } | null;
}

/**
 * WorkspaceEnv represents the current shell environment (local or WSL distro).
 */
export interface WorkspaceEnv {
    /**
     * "local" | "wsl"
     */
    "kind": string;
    "distro"?: string;
    "cwd": string;
}
