// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WSLDistro mirrors the Rust backend's `WslDistro` (used by the frontend).
 */
export interface WSLDistro {
    "name": string;
    "default": boolean;
    "running": boolean;
}
