// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the Wails-bound struct.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as shell$0 from "./internal/shell/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "./internal/types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workspace$0 from "./internal/workspace/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AgentEnableHooks announces hooks readiness for a given agent.
 */
export function AgentEnableHooks(args: $models.AgentEnableHooksArgs): $CancellablePromise<void> {
    return $Call.ByID(4213834771, args);
}

/**
 * AgentHooksStatus reports whether hooks are wired up. The frontend
 * expects a flat boolean (`boolean`).
 */
export function AgentHooksStatus(args: $models.AgentHooksStatusArgs): $CancellablePromise<boolean> {
    return $Call.ByID(1939283696, args);
}

/**
 * AiHttpRequest performs a single HTTP call.
 */
export function AiHttpRequest(args: $models.AiHttpRequestArgs): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3568388712, args);
}

/**
 * AiHttpStream opens a streaming HTTP call. Output flows over the
 * `OnEventEvent` event.
 */
export function AiHttpStream(args: $models.AiHttpStreamArgs): $CancellablePromise<void> {
    return $Call.ByID(433076263, args);
}

/**
 * AppConfigDir returns the per-user config directory (same as appDir).
 */
export function AppConfigDir(): $CancellablePromise<string> {
    return $Call.ByID(2227607177);
}

/**
 * AppDataDir returns the per-user data directory.
 */
export function AppDataDir(): $CancellablePromise<string> {
    return $Call.ByID(3857306371);
}

/**
 * AppHomeDir returns the user's home directory.
 */
export function AppHomeDir(): $CancellablePromise<string> {
    return $Call.ByID(3979356386);
}

/**
 * AppName returns the application name.
 */
export function AppName(): $CancellablePromise<string> {
    return $Call.ByID(3701255807);
}

/**
 * AppVersion returns the application version.
 */
export function AppVersion(): $CancellablePromise<string> {
    return $Call.ByID(1970741496);
}

/**
 * AutostartDisable disables it.
 */
export function AutostartDisable(): $CancellablePromise<void> {
    return $Call.ByID(2591011318);
}

/**
 * AutostartEnable enables OS-level autostart.
 */
export function AutostartEnable(): $CancellablePromise<void> {
    return $Call.ByID(3709685693);
}

/**
 * AutostartIsEnabled reports current state.
 */
export function AutostartIsEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(410284607);
}

/**
 * FsCanonicalize returns an absolute path with forward slashes.
 */
export function FsCanonicalize(path: string): $CancellablePromise<string> {
    return $Call.ByID(2612677170, path);
}

/**
 * FsCopy copies one or more paths into a destination directory.
 */
export function FsCopy(args: $models.FsCopyArgs): $CancellablePromise<void> {
    return $Call.ByID(2230388571, args);
}

/**
 * FsCreateDir creates a directory recursively.
 */
export function FsCreateDir(args: $models.FsCreateFileArgs): $CancellablePromise<void> {
    return $Call.ByID(1839682505, args);
}

/**
 * FsCreateFile creates an empty file.
 */
export function FsCreateFile(args: $models.FsCreateFileArgs): $CancellablePromise<void> {
    return $Call.ByID(1080590436, args);
}

/**
 * FsDelete removes a file or directory.
 */
export function FsDelete(args: $models.FsDeleteArgs): $CancellablePromise<void> {
    return $Call.ByID(2683678305, args);
}

/**
 * FsGlob matches a glob pattern and returns the envelope the frontend
 * expects: {hits: [{path, rel}], truncated}.
 */
export function FsGlob(args: $models.FsGlobArgs): $CancellablePromise<types$0.FsGlobResponse> {
    return $Call.ByID(2531664460, args);
}

/**
 * FsGrep runs a content search and returns the envelope the frontend
 * expects: {hits, truncated, filesScanned}. The Go side prefers ripgrep
 * when installed; falls back to an in-process scanner otherwise.
 */
export function FsGrep(args: $models.FsGrepArgs): $CancellablePromise<types$0.FsGrepResponse> {
    return $Call.ByID(3703800470, args);
}

/**
 * FsGrepInteractive is currently the same as FsGrep; the Rust version used
 * a long-running channel but for simplicity we return the full result set.
 */
export function FsGrepInteractive(args: $models.FsGrepInteractiveArgs): $CancellablePromise<types$0.FsGrepResponse> {
    return $Call.ByID(2078963710, args);
}

/**
 * FsListFiles walks a directory collecting file paths up to a cap. Mirrors
 * the Rust backend's `ListFilesResult` envelope ({files, truncated}).
 */
export function FsListFiles(args: $models.FsListFilesArgs): $CancellablePromise<types$0.FsListFilesResult> {
    return $Call.ByID(3561846565, args);
}

/**
 * FsReadDir lists directory entries.
 */
export function FsReadDir(args: $models.FsReadDirArgs): $CancellablePromise<types$0.DirEntry[] | null> {
    return $Call.ByID(3848596949, args);
}

/**
 * FsReadFile reads a file as UTF-8 text.
 */
export function FsReadFile(path: string): $CancellablePromise<types$0.ReadResult> {
    return $Call.ByID(2169230200, path);
}

/**
 * FsRename moves a path.
 */
export function FsRename(args: $models.FsRenameArgs): $CancellablePromise<void> {
    return $Call.ByID(345008640, args);
}

/**
 * FsSearch finds files by name substring. Returns the Rust envelope
 * ({hits: [{path, rel, name, isDir}], truncated}) so the explorer
 * component renders consistently with the Tauri build.
 */
export function FsSearch(args: $models.FsSearchArgs): $CancellablePromise<types$0.FsSearchResponse> {
    return $Call.ByID(3620415782, args);
}

/**
 * FsStat returns metadata for a path.
 */
export function FsStat(path: string): $CancellablePromise<types$0.FsStat> {
    return $Call.ByID(725087260, path);
}

/**
 * FsWatchAdd adds directories to the watcher.
 */
export function FsWatchAdd(args: $models.FsWatchAddArgs): $CancellablePromise<void> {
    return $Call.ByID(1652947700, args);
}

/**
 * FsWatchRemove removes directories from the watcher.
 */
export function FsWatchRemove(args: $models.FsWatchRemoveArgs): $CancellablePromise<void> {
    return $Call.ByID(145470333, args);
}

/**
 * FsWriteFile writes UTF-8 content.
 */
export function FsWriteFile(args: $models.FsWriteFileArgs): $CancellablePromise<void> {
    return $Call.ByID(1312764967, args);
}

/**
 * GetLaunchDir returns the directory the user passed at launch.
 */
export function GetLaunchDir(): $CancellablePromise<string | null> {
    return $Call.ByID(2923827015);
}

/**
 * GetLaunchFiles returns the files passed via "Open With" / CLI args.
 */
export function GetLaunchFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2677783087);
}

/**
 * GitCheckoutBranch switches branch.
 */
export function GitCheckoutBranch(args: $models.GitCheckoutBranchArgs): $CancellablePromise<void> {
    return $Call.ByID(395894751, args);
}

/**
 * GitCommit creates a commit. Returns {commitSha, summary} envelope.
 */
export function GitCommit(args: $models.GitCommitArgs): $CancellablePromise<types$0.GitCommitResult> {
    return $Call.ByID(1971060042, args);
}

/**
 * GitCommitFileDiff returns the diff for one file in a commit.
 */
export function GitCommitFileDiff(args: $models.GitCommitFileDiffArgs): $CancellablePromise<types$0.GitDiffContentResult> {
    return $Call.ByID(1264257307, args);
}

/**
 * GitCommitFiles returns files touched by a commit.
 */
export function GitCommitFiles(args: $models.GitCommitFilesArgs): $CancellablePromise<types$0.GitCommitFileChange[] | null> {
    return $Call.ByID(3346469837, args);
}

/**
 * GitDiff returns the unified diff for a path.
 */
export function GitDiff(args: $models.GitDiffArgs): $CancellablePromise<types$0.GitDiffResult> {
    return $Call.ByID(4088799792, args);
}

/**
 * GitDiffContent returns the side-by-side diff body.
 */
export function GitDiffContent(args: $models.GitDiffContentArgs): $CancellablePromise<types$0.GitDiffContentResult> {
    return $Call.ByID(1619936469, args);
}

/**
 * GitDiscard reverts working-tree changes.
 */
export function GitDiscard(args: $models.GitDiscardArgs): $CancellablePromise<void> {
    return $Call.ByID(3250690495, args);
}

/**
 * GitFetch fetches from origin.
 */
export function GitFetch(args: $models.GitFetchArgs): $CancellablePromise<void> {
    return $Call.ByID(3453556797, args);
}

/**
 * GitListBranches returns the local+worktree branches envelope.
 */
export function GitListBranches(args: $models.GitListBranchesArgs): $CancellablePromise<types$0.GitBranchListResult> {
    return $Call.ByID(2693102179, args);
}

/**
 * GitLog returns recent commits with full per-commit stats.
 */
export function GitLog(args: $models.GitLogArgs): $CancellablePromise<types$0.GitLogEntry[] | null> {
    return $Call.ByID(4286542579, args);
}

/**
 * GitPanelSnapshot returns the parsed panel snapshot (nested repo +
 * status envelope).
 */
export function GitPanelSnapshot(args: $models.GitPanelSnapshotArgs): $CancellablePromise<types$0.GitPanelSnapshot> {
    return $Call.ByID(921503755, args);
}

/**
 * GitPullFFOnly performs a fast-forward pull.
 */
export function GitPullFFOnly(args: $models.GitPullFFOnlyArgs): $CancellablePromise<void> {
    return $Call.ByID(1092076426, args);
}

/**
 * GitPush pushes the current branch. Returns {remote, branch, pushed}.
 */
export function GitPush(args: $models.GitPushArgs): $CancellablePromise<types$0.GitPushResult> {
    return $Call.ByID(4036251239, args);
}

/**
 * GitRemoteURL returns the remote URL (nullable when no remote).
 */
export function GitRemoteURL(args: $models.GitRemoteURLArgs): $CancellablePromise<string | null> {
    return $Call.ByID(1841623818, args);
}

/**
 * GitResolveRepo finds the repo root for a cwd. Returns the Rust
 * envelope `{repoRoot, branch, upstream, isDetached}` (nullable when
 * not inside a repo).
 */
export function GitResolveRepo(args: $models.GitResolveRepoArgs): $CancellablePromise<types$0.GitRepoInfo | null> {
    return $Call.ByID(907238885, args);
}

/**
 * GitShowCommit returns the unified diff for a commit.
 */
export function GitShowCommit(args: $models.GitShowCommitArgs): $CancellablePromise<types$0.GitDiffResult> {
    return $Call.ByID(2995252307, args);
}

/**
 * GitStage adds paths to the index.
 */
export function GitStage(args: $models.GitStageArgs): $CancellablePromise<void> {
    return $Call.ByID(1714641439, args);
}

/**
 * GitStatus returns the parsed status snapshot.
 */
export function GitStatus(args: $models.GitStatusArgs): $CancellablePromise<types$0.GitStatusSnapshot> {
    return $Call.ByID(1421317957, args);
}

/**
 * GitUnstage resets the index entries.
 */
export function GitUnstage(args: $models.GitUnstageArgs): $CancellablePromise<void> {
    return $Call.ByID(2384683490, args);
}

/**
 * HistoryCommands returns recorded commands matching the prefix (or every
 * command if no prefix is supplied), capped at `limit` entries.
 */
export function HistoryCommands(args: $models.HistoryCommandsArgs): $CancellablePromise<string[] | null> {
    return $Call.ByID(3647402229, args);
}

/**
 * HistoryList returns the last N entries.
 */
export function HistoryList(args: $models.HistoryListArgs): $CancellablePromise<string[] | null> {
    return $Call.ByID(163493247, args);
}

/**
 * HistoryRecord appends a command.
 */
export function HistoryRecord(args: $models.HistoryRecordArgs): $CancellablePromise<void> {
    return $Call.ByID(3518178174, args);
}

/**
 * HistorySuggest returns fuzzy matches.
 */
export function HistorySuggest(args: $models.HistorySuggestArgs): $CancellablePromise<string[] | null> {
    return $Call.ByID(2280160435, args);
}

/**
 * ListSubdirs returns the names of immediate subdirectories of `path`.
 * Used by the status-bar breadcrumb to populate the dropdown. Hidden
 * entries are filtered by default; pass `showHidden: true` to include
 * dot-prefixed names.
 */
export function ListSubdirs(args: $models.ListSubdirsArgs): $CancellablePromise<string[] | null> {
    return $Call.ByID(1268701089, args);
}

/**
 * LmPing pings a local model endpoint.
 */
export function LmPing(args: $models.LmPingArgs): $CancellablePromise<number> {
    return $Call.ByID(245434770, args);
}

/**
 * LspDetect reports whether a binary exists.
 */
export function LspDetect(command: string): $CancellablePromise<boolean> {
    return $Call.ByID(2276766463, command);
}

/**
 * LspHostPID returns the host's process ID.
 */
export function LspHostPID(): $CancellablePromise<number> {
    return $Call.ByID(1969424299);
}

/**
 * LspKill terminates a session.
 */
export function LspKill(id: number): $CancellablePromise<void> {
    return $Call.ByID(711497168, id);
}

/**
 * LspResolveRoot walks up from `path` looking for any marker.
 */
export function LspResolveRoot(args: $models.LspResolveRootArgs): $CancellablePromise<string> {
    return $Call.ByID(1212116076, args);
}

/**
 * LspSend writes a JSON-RPC message to the LSP server.
 */
export function LspSend(args: $models.LspSendArgs): $CancellablePromise<void> {
    return $Call.ByID(2603101438, args);
}

/**
 * LspSpawn starts a language server.
 */
export function LspSpawn(args: $models.LspSpawnArgs): $CancellablePromise<number> {
    return $Call.ByID(2909710655, args);
}

/**
 * McpCallTool calls an MCP tool by name with the given arguments.
 */
export function McpCallTool(name: string, args: { [_ in string]?: any } | null): $CancellablePromise<any> {
    return $Call.ByID(1912958229, name, args);
}

/**
 * McpListTools returns the list of available MCP tools.
 */
export function McpListTools(): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(660396682);
}

/**
 * OpenSettingsWindow opens the settings page in a new window.
 * If the settings window already exists, it is focused instead.
 */
export function OpenSettingsWindow(args: $models.OpenSettingsWindowArgs): $CancellablePromise<void> {
    return $Call.ByID(3185921024, args);
}

/**
 * OpenerOpenPath opens a path with the OS default app.
 */
export function OpenerOpenPath(args: $models.OpenerOpenPathArgs): $CancellablePromise<void> {
    return $Call.ByID(441191249, args);
}

/**
 * OpenerOpenURL opens a URL in the default browser.
 */
export function OpenerOpenURL(args: $models.OpenerOpenURLArgs): $CancellablePromise<void> {
    return $Call.ByID(576916987, args);
}

/**
 * OpenerRevealItem opens the file explorer at `path`.
 */
export function OpenerRevealItem(args: $models.OpenerRevealItemArgs): $CancellablePromise<void> {
    return $Call.ByID(2325762312, args);
}

/**
 * ProcessExit terminates the app.
 */
export function ProcessExit(args: $models.ProcessExitArgs): $CancellablePromise<void> {
    return $Call.ByID(3449883610, args);
}

/**
 * ProcessRelaunch re-launches the binary with the same args.
 */
export function ProcessRelaunch(): $CancellablePromise<void> {
    return $Call.ByID(3221083376);
}

/**
 * PtyClose terminates a PTY session.
 */
export function PtyClose(id: number): $CancellablePromise<void> {
    return $Call.ByID(2629681492, id);
}

/**
 * PtyCloseAll kills every PTY session.
 */
export function PtyCloseAll(): $CancellablePromise<void> {
    return $Call.ByID(2101817839);
}

/**
 * PtyHasForegroundJob is an alias used by the AI workflow.
 */
export function PtyHasForegroundJob(id: number): $CancellablePromise<boolean> {
    return $Call.ByID(3959191392, id);
}

/**
 * PtyHasForegroundProcess mirrors the original Rust command.
 */
export function PtyHasForegroundProcess(id: number): $CancellablePromise<boolean> {
    return $Call.ByID(3291748438, id);
}

/**
 * PtyListShells returns the shells available on this machine.
 */
export function PtyListShells(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1598781883);
}

/**
 * PtyOpen starts a new PTY session.
 */
export function PtyOpen(args: $models.PtyOpenArgs): $CancellablePromise<number> {
    return $Call.ByID(4044397528, args);
}

/**
 * PtyReadOutput used to be a poll fallback for the Wails event bus. We
 * removed the outputBuf and the polling path; the new pump emits
 * `pty:<id>` events directly. The method is kept as a no-op stub so a
 * stale frontend build (calling `pty_read_output`) doesn't get a 404 —
 * it just returns nil bytes.
 */
export function PtyReadOutput(id: number): $CancellablePromise<string | null> {
    return $Call.ByID(2696612937, id);
}

/**
 * PtyResize changes the PTY geometry.
 */
export function PtyResize(args: $models.PtyResizeArgs): $CancellablePromise<void> {
    return $Call.ByID(1257662920, args);
}

/**
 * PtyShellName returns the executable name (pwsh, zsh, ...) for a session.
 */
export function PtyShellName(id: number): $CancellablePromise<string> {
    return $Call.ByID(2638903561, id);
}

/**
 * PtyStart begins forwarding PTY output. The frontend must subscribe to the
 * `pty:<id>` event BEFORE calling this, so shell startup bytes don't race
 * ahead of the unbuffered Wails event bus and get dropped.
 */
export function PtyStart(args: $models.PtyStartArgs): $CancellablePromise<void> {
    return $Call.ByID(2771601004, args);
}

/**
 * PtyWrite sends stdin data to a PTY session.
 */
export function PtyWrite(args: $models.PtyWriteArgs): $CancellablePromise<void> {
    return $Call.ByID(2248404703, args);
}

/**
 * SecretsDelete removes a keyring entry.
 */
export function SecretsDelete(args: $models.SecretsDeleteArgs): $CancellablePromise<void> {
    return $Call.ByID(3603448937, args);
}

/**
 * SecretsGet reads a keyring entry.
 */
export function SecretsGet(args: $models.SecretsGetArgs): $CancellablePromise<string | null> {
    return $Call.ByID(1405262442, args);
}

/**
 * SecretsGetAll returns the values for many accounts.
 */
export function SecretsGetAll(args: $models.SecretsGetAllArgs): $CancellablePromise<(string | null)[] | null> {
    return $Call.ByID(3034428625, args);
}

/**
 * SecretsSet writes a keyring entry.
 */
export function SecretsSet(args: $models.SecretsSetArgs): $CancellablePromise<void> {
    return $Call.ByID(675316294, args);
}

/**
 * ShellBgKill terminates a job.
 */
export function ShellBgKill(args: $models.ShellBgKillArgs): $CancellablePromise<void> {
    return $Call.ByID(3841368694, args);
}

/**
 * ShellBgList returns the list of job IDs.
 */
export function ShellBgList(): $CancellablePromise<shell$0.BgProcessInfo[] | null> {
    return $Call.ByID(2903053758);
}

/**
 * ShellBgLogs returns captured output.
 */
export function ShellBgLogs(args: $models.ShellBgLogsArgs): $CancellablePromise<string> {
    return $Call.ByID(2169289793, args);
}

/**
 * ShellBgSpawn starts a background process.
 */
export function ShellBgSpawn(args: $models.ShellBgSpawnArgs): $CancellablePromise<number> {
    return $Call.ByID(1790134377, args);
}

/**
 * ShellRunCommand runs a one-shot shell command.
 */
export function ShellRunCommand(args: $models.ShellRunCommandArgs): $CancellablePromise<string> {
    return $Call.ByID(3706160855, args);
}

/**
 * ShellSessionClose closes an interactive session.
 */
export function ShellSessionClose(args: $models.ShellSessionCloseArgs): $CancellablePromise<void> {
    return $Call.ByID(984094129, args);
}

/**
 * ShellSessionOpen starts an interactive session.
 */
export function ShellSessionOpen(args: $models.ShellSessionOpenArgs): $CancellablePromise<number> {
    return $Call.ByID(12650647, args);
}

/**
 * ShellSessionRun sends a command to an existing session and returns the
 * captured output, exit code, and post-command cwd.
 */
export function ShellSessionRun(args: $models.ShellSessionRunArgs): $CancellablePromise<types$0.ShellSessionResult | null> {
    return $Call.ByID(298918284, args);
}

/**
 * StoreLoad reads a JSON bag.
 */
export function StoreLoad(args: $models.StoreLoadArgs): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2841886614, args);
}

/**
 * StoreSave writes a JSON bag.
 */
export function StoreSave(args: $models.StoreSaveArgs): $CancellablePromise<void> {
    return $Call.ByID(2501849843, args);
}

/**
 * UpdaterCheck returns the latest release info (or null when up to date).
 */
export function UpdaterCheck(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3484517082);
}

/**
 * WindowClose closes the window with the given name.
 */
export function WindowClose(name: string): $CancellablePromise<void> {
    return $Call.ByID(1474073651, name);
}

/**
 * WindowFocus brings the named window to focus.
 */
export function WindowFocus(name: string): $CancellablePromise<void> {
    return $Call.ByID(1927019587, name);
}

/**
 * WindowGetAll returns the titles of all open windows.
 */
export function WindowGetAll(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1233749186);
}

/**
 * WindowNew creates a new application window.
 */
export function WindowNew(title: string, width: number, height: number): $CancellablePromise<void> {
    return $Call.ByID(155836513, title, width, height);
}

/**
 * WorkspaceAuthorize marks a directory as allowed.
 */
export function WorkspaceAuthorize(args: $models.WorkspaceAuthorizeArgs): $CancellablePromise<void> {
    return $Call.ByID(851984129, args);
}

/**
 * WorkspaceCurrentDir returns the active cwd.
 */
export function WorkspaceCurrentDir(): $CancellablePromise<string> {
    return $Call.ByID(316211366);
}

/**
 * WorkspacePickDirectory opens a native directory picker and returns the
 * chosen path (empty string if the user cancelled). The picked directory
 * is also authorised so the file explorer can browse it without a prompt.
 */
export function WorkspacePickDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1144727078);
}

/**
 * WorkspaceSetCwd updates the global active cwd (default dir for the dir
 * picker and the cwd fallback for new PTYs). Called after switching a
 * workspace/space so CurrentDir follows the new home instead of staying on
 * the first-launch directory.
 */
export function WorkspaceSetCwd(args: $models.WorkspaceSetCwdArgs): $CancellablePromise<void> {
    return $Call.ByID(588013380, args);
}

/**
 * WslDefaultDistro returns the default WSL distro.
 */
export function WslDefaultDistro(): $CancellablePromise<string> {
    return $Call.ByID(3872635401);
}

/**
 * WslHome returns the home directory of a WSL distro.
 */
export function WslHome(args: $models.WslHomeArgs): $CancellablePromise<string> {
    return $Call.ByID(1623803762, args);
}

/**
 * WslListDistros returns the available WSL distros (Windows only). The
 * Rust envelope is `[{name, default}]` so the frontend can highlight the
 * active one.
 */
export function WslListDistros(): $CancellablePromise<workspace$0.WSLDistro[] | null> {
    return $Call.ByID(2241427587);
}
