// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "./internal/types/models.js";

/**
 * AgentEnableHooksArgs is the request body.
 */
export interface AgentEnableHooksArgs {
    "agent": string;
}

/**
 * AgentHooksStatusArgs is the request body.
 */
export interface AgentHooksStatusArgs {
    "agent": string;
}

/**
 * AiHttpRequestArgs is the request body.
 */
export type AiHttpRequestArgs = types$0.AiHttpRequestArgs;

/**
 * AiHttpStreamArgs is the request body.
 */
export type AiHttpStreamArgs = types$0.AiHttpStreamArgs;

/**
 * FsCopyArgs is the request body.
 */
export type FsCopyArgs = types$0.FsCopyArgs;

/**
 * FsCreateFileArgs is the request body.
 */
export type FsCreateFileArgs = types$0.FsCreateArgs;

/**
 * FsDeleteArgs is the request body.
 */
export type FsDeleteArgs = types$0.FsDeleteArgs;

/**
 * FsGlobArgs is the request body.
 */
export type FsGlobArgs = types$0.FsGlobArgs;

/**
 * FsGrepArgs is the request body.
 */
export type FsGrepArgs = types$0.FsGrepArgs;

/**
 * FsGrepInteractiveArgs mirrors the streaming variant.
 */
export type FsGrepInteractiveArgs = types$0.FsGrepArgs;

/**
 * FsListFilesArgs is the request body.
 */
export type FsListFilesArgs = types$0.FsListFilesArgs;

/**
 * FsReadDirArgs mirrors the request shape.
 */
export type FsReadDirArgs = types$0.FsReadDirArgs;

/**
 * FsRenameArgs is the request body.
 */
export type FsRenameArgs = types$0.FsRenameArgs;

/**
 * FsSearchArgs is the request body.
 */
export type FsSearchArgs = types$0.FsSearchArgs;

/**
 * FsWatchAddArgs is the request body.
 */
export type FsWatchAddArgs = types$0.FsWatchArgs;

/**
 * FsWatchRemoveArgs is the request body.
 */
export type FsWatchRemoveArgs = types$0.FsWatchArgs;

/**
 * FsWriteFileArgs is the request body.
 */
export type FsWriteFileArgs = types$0.FsWriteArgs;

/**
 * GitCheckoutBranchArgs is the request body.
 */
export interface GitCheckoutBranchArgs {
    "repoRoot": string;
    "branch": string;
}

/**
 * GitCommitArgs is the request body.
 */
export interface GitCommitArgs {
    "repoRoot": string;
    "message": string;
}

/**
 * GitCommitFileDiffArgs is the request body.
 */
export interface GitCommitFileDiffArgs {
    "repoRoot": string;
    "sha": string;
    "path": string;
    "originalPath"?: string;
}

/**
 * GitCommitFilesArgs is the request body.
 */
export type GitCommitFilesArgs = GitShowCommitArgs;

/**
 * GitDiffArgs is the request body.
 */
export interface GitDiffArgs {
    "repoRoot": string;
    "path": string;
    "staged": boolean;
}

/**
 * GitDiffContentArgs is the request body.
 */
export interface GitDiffContentArgs {
    "repoRoot": string;
    "path": string;
    "staged": boolean;
    "originalPath"?: string;
}

/**
 * GitDiscardArgs is the request body (entries: [{path, untracked}]).
 */
export interface GitDiscardArgs {
    "repoRoot": string;
    "entries": types$0.GitDiscardEntry[] | null;
}

/**
 * GitFetchArgs is the request body.
 */
export interface GitFetchArgs {
    "repoRoot": string;
}

/**
 * GitListBranchesArgs is the request body.
 */
export type GitListBranchesArgs = GitFetchArgs;

/**
 * GitLogArgs is the request body.
 */
export interface GitLogArgs {
    "repoRoot": string;
    "limit"?: number;
    "beforeSha"?: string | null;
}

/**
 * GitPanelSnapshotArgs is the request body.
 */
export interface GitPanelSnapshotArgs {
    "cwd": string;
}

/**
 * GitPullFFOnlyArgs is the request body.
 */
export type GitPullFFOnlyArgs = GitFetchArgs;

/**
 * GitPushArgs is the request body.
 */
export type GitPushArgs = GitFetchArgs;

/**
 * GitRemoteURLArgs is the request body.
 */
export interface GitRemoteURLArgs {
    "repoRoot": string;
    "name"?: string;
}

/**
 * GitResolveRepoArgs is the request body for git_resolve_repo.
 */
export interface GitResolveRepoArgs {
    "cwd": string;
}

/**
 * GitShowCommitArgs is the request body.
 */
export interface GitShowCommitArgs {
    "repoRoot": string;
    "sha": string;
}

/**
 * GitStageArgs is the request body.
 */
export interface GitStageArgs {
    "repoRoot": string;
    "paths": string[] | null;
}

/**
 * GitStatusArgs is the request body.
 */
export interface GitStatusArgs {
    "repoRoot": string;
}

/**
 * GitUnstageArgs is the request body.
 */
export type GitUnstageArgs = GitStageArgs;

/**
 * HistoryCommandsArgs is the request body.
 */
export interface HistoryCommandsArgs {
    "prefix": string;
    "limit": number;
}

/**
 * HistoryListArgs is the request body.
 */
export type HistoryListArgs = types$0.HistoryListArgs;

/**
 * HistoryRecordArgs is the request body.
 */
export type HistoryRecordArgs = types$0.HistoryRecordArgs;

/**
 * HistorySuggestArgs is the request body.
 */
export type HistorySuggestArgs = types$0.HistorySuggestArgs;

/**
 * ListSubdirsArgs is the request body.
 */
export interface ListSubdirsArgs {
    "path": string;
    "showHidden": boolean;
    "workspace": types$0.WorkspaceEnv;
}

/**
 * LmPingArgs is the request body.
 */
export type LmPingArgs = types$0.LmPingArgs;

/**
 * LspResolveRootArgs is the request body — both path and markers must be
 * passed together because Wails can only marshal a single struct, not
 * multiple positional args.
 */
export interface LspResolveRootArgs {
    "path": string;
    "markers": string[] | null;
}

/**
 * LspSendArgs is the request body.
 */
export interface LspSendArgs {
    "id": number;
    "message": string;
}

/**
 * LspSpawnArgs mirrors the request shape.
 */
export type LspSpawnArgs = types$0.LspSpawnArgs;

/**
 * OpenSettingsWindowArgs is the request body.
 */
export interface OpenSettingsWindowArgs {
    "tab": string | null;
}

/**
 * OpenerOpenPathArgs is the request body.
 */
export interface OpenerOpenPathArgs {
    "path": string;
}

/**
 * OpenerOpenURLArgs is the request body.
 */
export interface OpenerOpenURLArgs {
    "url": string;
}

/**
 * OpenerRevealItemArgs is the request body.
 */
export type OpenerRevealItemArgs = OpenerOpenPathArgs;

/**
 * ProcessExitArgs is the request body.
 */
export interface ProcessExitArgs {
    "code": number;
}

/**
 * PtyOpenArgs is the request body for PtyOpen.
 */
export type PtyOpenArgs = types$0.PtyOpenArgs;

/**
 * PtyResizeArgs is the request body for PtyResize.
 */
export interface PtyResizeArgs {
    "id": number;
    "cols": number;
    "rows": number;
}

/**
 * PtyStartArgs is the request body for PtyStart.
 */
export interface PtyStartArgs {
    "id": number;
}

/**
 * PtyWriteArgs is the request body for PtyWrite.
 */
export interface PtyWriteArgs {
    "id": number;
    "data": string | null;
}

/**
 * SecretsDeleteArgs is the request body.
 */
export interface SecretsDeleteArgs {
    "service": string;
    "account": string;
}

/**
 * SecretsGetAllArgs is the request body.
 */
export interface SecretsGetAllArgs {
    "service": string;
    "accounts": string[] | null;
}

/**
 * SecretsGetArgs is the request body.
 */
export interface SecretsGetArgs {
    "service": string;
    "account": string;
}

/**
 * SecretsSetArgs is the request body.
 */
export interface SecretsSetArgs {
    "service": string;
    "account": string;
    "password": string;
}

/**
 * ShellBgKillArgs is the request body.
 */
export type ShellBgKillArgs = types$0.ShellBgKillArgs;

/**
 * ShellBgLogsArgs is the request body.
 */
export type ShellBgLogsArgs = types$0.ShellBgLogsArgs;

/**
 * ShellBgSpawnArgs is the request body.
 */
export type ShellBgSpawnArgs = types$0.ShellBgSpawnArgs;

/**
 * ShellRunCommandArgs is the request body.
 */
export type ShellRunCommandArgs = types$0.ShellRunArgs;

/**
 * ShellSessionCloseArgs is the request body.
 */
export interface ShellSessionCloseArgs {
    "id": number;
}

/**
 * ShellSessionOpenArgs is the request body.
 */
export type ShellSessionOpenArgs = types$0.ShellSessionOpenArgs;

/**
 * ShellSessionRunArgs is the request body.
 */
export type ShellSessionRunArgs = types$0.ShellSessionRunArgs;

/**
 * StoreLoadArgs is the request body.
 */
export type StoreLoadArgs = types$0.StoreLoadArgs;

/**
 * StoreSaveArgs is the request body.
 */
export type StoreSaveArgs = types$0.StoreSaveArgs;

/**
 * WorkspaceAuthorizeArgs is the request body. `path` (not `dir`) so the
 * frontend can pass a single named arg that matches every other workspace
 * command's shape.
 */
export interface WorkspaceAuthorizeArgs {
    "path": string;
}

/**
 * WorkspaceSetCwdArgs is the request body for WorkspaceSetCwd.
 */
export interface WorkspaceSetCwdArgs {
    "path": string;
}

/**
 * WslHomeArgs is the request body.
 */
export interface WslHomeArgs {
    "distro": string;
}
