// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AgentEnableHooks(arg1) {
  return window['go']['main']['App']['AgentEnableHooks'](arg1);
}

export function AgentHooksStatus(arg1) {
  return window['go']['main']['App']['AgentHooksStatus'](arg1);
}

export function AiHttpRequest(arg1) {
  return window['go']['main']['App']['AiHttpRequest'](arg1);
}

export function AiHttpStream(arg1) {
  return window['go']['main']['App']['AiHttpStream'](arg1);
}

export function AppConfigDir() {
  return window['go']['main']['App']['AppConfigDir']();
}

export function AppDataDir() {
  return window['go']['main']['App']['AppDataDir']();
}

export function AppHomeDir() {
  return window['go']['main']['App']['AppHomeDir']();
}

export function AutostartDisable() {
  return window['go']['main']['App']['AutostartDisable']();
}

export function AutostartEnable() {
  return window['go']['main']['App']['AutostartEnable']();
}

export function AutostartIsEnabled() {
  return window['go']['main']['App']['AutostartIsEnabled']();
}

export function FsCanonicalize(arg1) {
  return window['go']['main']['App']['FsCanonicalize'](arg1);
}

export function FsCopy(arg1) {
  return window['go']['main']['App']['FsCopy'](arg1);
}

export function FsCreateDir(arg1) {
  return window['go']['main']['App']['FsCreateDir'](arg1);
}

export function FsCreateFile(arg1) {
  return window['go']['main']['App']['FsCreateFile'](arg1);
}

export function FsDelete(arg1) {
  return window['go']['main']['App']['FsDelete'](arg1);
}

export function FsGlob(arg1) {
  return window['go']['main']['App']['FsGlob'](arg1);
}

export function FsGrep(arg1) {
  return window['go']['main']['App']['FsGrep'](arg1);
}

export function FsGrepInteractive(arg1) {
  return window['go']['main']['App']['FsGrepInteractive'](arg1);
}

export function FsListFiles(arg1) {
  return window['go']['main']['App']['FsListFiles'](arg1);
}

export function FsReadDir(arg1) {
  return window['go']['main']['App']['FsReadDir'](arg1);
}

export function FsReadFile(arg1) {
  return window['go']['main']['App']['FsReadFile'](arg1);
}

export function FsRename(arg1) {
  return window['go']['main']['App']['FsRename'](arg1);
}

export function FsSearch(arg1) {
  return window['go']['main']['App']['FsSearch'](arg1);
}

export function FsStat(arg1) {
  return window['go']['main']['App']['FsStat'](arg1);
}

export function FsWatchAdd(arg1) {
  return window['go']['main']['App']['FsWatchAdd'](arg1);
}

export function FsWatchRemove(arg1) {
  return window['go']['main']['App']['FsWatchRemove'](arg1);
}

export function FsWriteFile(arg1) {
  return window['go']['main']['App']['FsWriteFile'](arg1);
}

export function GetLaunchDir() {
  return window['go']['main']['App']['GetLaunchDir']();
}

export function GetLaunchFiles() {
  return window['go']['main']['App']['GetLaunchFiles']();
}

export function GitCheckoutBranch(arg1) {
  return window['go']['main']['App']['GitCheckoutBranch'](arg1);
}

export function GitCommit(arg1) {
  return window['go']['main']['App']['GitCommit'](arg1);
}

export function GitCommitFileDiff(arg1) {
  return window['go']['main']['App']['GitCommitFileDiff'](arg1);
}

export function GitCommitFiles(arg1) {
  return window['go']['main']['App']['GitCommitFiles'](arg1);
}

export function GitDiff(arg1) {
  return window['go']['main']['App']['GitDiff'](arg1);
}

export function GitDiffContent(arg1) {
  return window['go']['main']['App']['GitDiffContent'](arg1);
}

export function GitDiscard(arg1) {
  return window['go']['main']['App']['GitDiscard'](arg1);
}

export function GitFetch(arg1) {
  return window['go']['main']['App']['GitFetch'](arg1);
}

export function GitListBranches(arg1) {
  return window['go']['main']['App']['GitListBranches'](arg1);
}

export function GitLog(arg1) {
  return window['go']['main']['App']['GitLog'](arg1);
}

export function GitPanelSnapshot(arg1) {
  return window['go']['main']['App']['GitPanelSnapshot'](arg1);
}

export function GitPullFFOnly(arg1) {
  return window['go']['main']['App']['GitPullFFOnly'](arg1);
}

export function GitPush(arg1) {
  return window['go']['main']['App']['GitPush'](arg1);
}

export function GitRemoteURL(arg1) {
  return window['go']['main']['App']['GitRemoteURL'](arg1);
}

export function GitResolveRepo(arg1) {
  return window['go']['main']['App']['GitResolveRepo'](arg1);
}

export function GitShowCommit(arg1) {
  return window['go']['main']['App']['GitShowCommit'](arg1);
}

export function GitStage(arg1) {
  return window['go']['main']['App']['GitStage'](arg1);
}

export function GitStatus(arg1) {
  return window['go']['main']['App']['GitStatus'](arg1);
}

export function GitUnstage(arg1) {
  return window['go']['main']['App']['GitUnstage'](arg1);
}

export function HistoryCommands(arg1) {
  return window['go']['main']['App']['HistoryCommands'](arg1);
}

export function HistoryList(arg1) {
  return window['go']['main']['App']['HistoryList'](arg1);
}

export function HistoryRecord(arg1) {
  return window['go']['main']['App']['HistoryRecord'](arg1);
}

export function HistorySuggest(arg1) {
  return window['go']['main']['App']['HistorySuggest'](arg1);
}

export function ListSubdirs(arg1) {
  return window['go']['main']['App']['ListSubdirs'](arg1);
}

export function LmPing(arg1) {
  return window['go']['main']['App']['LmPing'](arg1);
}

export function LspDetect(arg1) {
  return window['go']['main']['App']['LspDetect'](arg1);
}

export function LspHostPID() {
  return window['go']['main']['App']['LspHostPID']();
}

export function LspKill(arg1) {
  return window['go']['main']['App']['LspKill'](arg1);
}

export function LspResolveRoot(arg1) {
  return window['go']['main']['App']['LspResolveRoot'](arg1);
}

export function LspSend(arg1) {
  return window['go']['main']['App']['LspSend'](arg1);
}

export function LspSpawn(arg1) {
  return window['go']['main']['App']['LspSpawn'](arg1);
}

export function OpenSettingsWindow(arg1) {
  return window['go']['main']['App']['OpenSettingsWindow'](arg1);
}

export function OpenerOpenPath(arg1) {
  return window['go']['main']['App']['OpenerOpenPath'](arg1);
}

export function OpenerOpenURL(arg1) {
  return window['go']['main']['App']['OpenerOpenURL'](arg1);
}

export function OpenerRevealItem(arg1) {
  return window['go']['main']['App']['OpenerRevealItem'](arg1);
}

export function ProcessExit(arg1) {
  return window['go']['main']['App']['ProcessExit'](arg1);
}

export function ProcessRelaunch() {
  return window['go']['main']['App']['ProcessRelaunch']();
}

export function PtyClose(arg1) {
  return window['go']['main']['App']['PtyClose'](arg1);
}

export function PtyCloseAll() {
  return window['go']['main']['App']['PtyCloseAll']();
}

export function PtyHasForegroundJob(arg1) {
  return window['go']['main']['App']['PtyHasForegroundJob'](arg1);
}

export function PtyHasForegroundProcess(arg1) {
  return window['go']['main']['App']['PtyHasForegroundProcess'](arg1);
}

export function PtyListShells() {
  return window['go']['main']['App']['PtyListShells']();
}

export function PtyOpen(arg1) {
  return window['go']['main']['App']['PtyOpen'](arg1);
}

export function PtyReadOutput(arg1) {
  return window['go']['main']['App']['PtyReadOutput'](arg1);
}

export function PtyResize(arg1) {
  return window['go']['main']['App']['PtyResize'](arg1);
}

export function PtyShellName(arg1) {
  return window['go']['main']['App']['PtyShellName'](arg1);
}

export function PtyWrite(arg1) {
  return window['go']['main']['App']['PtyWrite'](arg1);
}

export function SecretsDelete(arg1) {
  return window['go']['main']['App']['SecretsDelete'](arg1);
}

export function SecretsGet(arg1) {
  return window['go']['main']['App']['SecretsGet'](arg1);
}

export function SecretsGetAll(arg1) {
  return window['go']['main']['App']['SecretsGetAll'](arg1);
}

export function SecretsSet(arg1) {
  return window['go']['main']['App']['SecretsSet'](arg1);
}

export function ShellBgKill(arg1) {
  return window['go']['main']['App']['ShellBgKill'](arg1);
}

export function ShellBgList() {
  return window['go']['main']['App']['ShellBgList']();
}

export function ShellBgLogs(arg1) {
  return window['go']['main']['App']['ShellBgLogs'](arg1);
}

export function ShellBgSpawn(arg1) {
  return window['go']['main']['App']['ShellBgSpawn'](arg1);
}

export function ShellRunCommand(arg1) {
  return window['go']['main']['App']['ShellRunCommand'](arg1);
}

export function ShellSessionClose(arg1) {
  return window['go']['main']['App']['ShellSessionClose'](arg1);
}

export function ShellSessionOpen(arg1) {
  return window['go']['main']['App']['ShellSessionOpen'](arg1);
}

export function ShellSessionRun(arg1) {
  return window['go']['main']['App']['ShellSessionRun'](arg1);
}

export function StoreLoad(arg1) {
  return window['go']['main']['App']['StoreLoad'](arg1);
}

export function StoreSave(arg1) {
  return window['go']['main']['App']['StoreSave'](arg1);
}

export function UpdaterCheck() {
  return window['go']['main']['App']['UpdaterCheck']();
}

export function WorkspaceAuthorize(arg1) {
  return window['go']['main']['App']['WorkspaceAuthorize'](arg1);
}

export function WorkspaceCurrentDir() {
  return window['go']['main']['App']['WorkspaceCurrentDir']();
}

export function WorkspacePickDirectory() {
  return window['go']['main']['App']['WorkspacePickDirectory']();
}

export function WslDefaultDistro() {
  return window['go']['main']['App']['WslDefaultDistro']();
}

export function WslHome(arg1) {
  return window['go']['main']['App']['WslHome'](arg1);
}

export function WslListDistros() {
  return window['go']['main']['App']['WslListDistros']();
}
