// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {types} from '../models';
import {shell} from '../models';
import {workspace} from '../models';

export function AgentEnableHooks(arg1:main.AgentEnableHooksArgs):Promise<void>;

export function AgentHooksStatus(arg1:main.AgentHooksStatusArgs):Promise<boolean>;

export function AiHttpRequest(arg1:types.AiHttpRequestArgs):Promise<Record<string, any>>;

export function AiHttpStream(arg1:types.AiHttpStreamArgs):Promise<void>;

export function AppConfigDir():Promise<string>;

export function AppDataDir():Promise<string>;

export function AppHomeDir():Promise<string>;

export function AutostartDisable():Promise<void>;

export function AutostartEnable():Promise<void>;

export function AutostartIsEnabled():Promise<boolean>;

export function FsCanonicalize(arg1:string):Promise<string>;

export function FsCopy(arg1:types.FsCopyArgs):Promise<void>;

export function FsCreateDir(arg1:types.FsCreateArgs):Promise<void>;

export function FsCreateFile(arg1:types.FsCreateArgs):Promise<void>;

export function FsDelete(arg1:types.FsDeleteArgs):Promise<void>;

export function FsGlob(arg1:types.FsGlobArgs):Promise<types.FsGlobResponse>;

export function FsGrep(arg1:types.FsGrepArgs):Promise<types.FsGrepResponse>;

export function FsGrepInteractive(arg1:types.FsGrepArgs):Promise<types.FsGrepResponse>;

export function FsListFiles(arg1:types.FsListFilesArgs):Promise<types.FsListFilesResult>;

export function FsReadDir(arg1:types.FsReadDirArgs):Promise<Array<types.DirEntry>>;

export function FsReadFile(arg1:string):Promise<types.ReadResult>;

export function FsRename(arg1:types.FsRenameArgs):Promise<void>;

export function FsSearch(arg1:types.FsSearchArgs):Promise<types.FsSearchResponse>;

export function FsStat(arg1:string):Promise<types.FsStat>;

export function FsWatchAdd(arg1:types.FsWatchArgs):Promise<void>;

export function FsWatchRemove(arg1:types.FsWatchArgs):Promise<void>;

export function FsWriteFile(arg1:types.FsWriteArgs):Promise<void>;

export function GitCheckoutBranch(arg1:main.GitCheckoutBranchArgs):Promise<void>;

export function GitCommit(arg1:main.GitCommitArgs):Promise<types.GitCommitResult>;

export function GitCommitFileDiff(arg1:main.GitCommitFileDiffArgs):Promise<types.GitDiffContentResult>;

export function GitCommitFiles(arg1:main.GitShowCommitArgs):Promise<Array<types.GitCommitFileChange>>;

export function GitDiff(arg1:main.GitDiffArgs):Promise<types.GitDiffResult>;

export function GitDiffContent(arg1:main.GitDiffContentArgs):Promise<types.GitDiffContentResult>;

export function GitDiscard(arg1:main.GitDiscardArgs):Promise<void>;

export function GitFetch(arg1:main.GitFetchArgs):Promise<void>;

export function GitListBranches(arg1:main.GitFetchArgs):Promise<types.GitBranchListResult>;

export function GitLog(arg1:main.GitLogArgs):Promise<Array<types.GitLogEntry>>;

export function GitPanelSnapshot(arg1:main.GitPanelSnapshotArgs):Promise<types.GitPanelSnapshot>;

export function GitPullFFOnly(arg1:main.GitFetchArgs):Promise<void>;

export function GitPush(arg1:main.GitFetchArgs):Promise<types.GitPushResult>;

export function GitRemoteURL(arg1:main.GitRemoteURLArgs):Promise<any>;

export function GitResolveRepo(arg1:main.GitResolveRepoArgs):Promise<types.GitRepoInfo>;

export function GitShowCommit(arg1:main.GitShowCommitArgs):Promise<types.GitDiffResult>;

export function GitStage(arg1:main.GitStageArgs):Promise<void>;

export function GitStatus(arg1:main.GitStatusArgs):Promise<types.GitStatusSnapshot>;

export function GitUnstage(arg1:main.GitStageArgs):Promise<void>;

export function HistoryCommands(arg1:main.HistoryCommandsArgs):Promise<Array<string>>;

export function HistoryList(arg1:types.HistoryListArgs):Promise<Array<string>>;

export function HistoryRecord(arg1:types.HistoryRecordArgs):Promise<void>;

export function HistorySuggest(arg1:types.HistorySuggestArgs):Promise<Array<string>>;

export function ListSubdirs(arg1:main.ListSubdirsArgs):Promise<Array<string>>;

export function LmPing(arg1:types.LmPingArgs):Promise<number>;

export function LspDetect(arg1:string):Promise<boolean>;

export function LspHostPID():Promise<number>;

export function LspKill(arg1:number):Promise<void>;

export function LspResolveRoot(arg1:main.LspResolveRootArgs):Promise<string>;

export function LspSend(arg1:main.LspSendArgs):Promise<void>;

export function LspSpawn(arg1:types.LspSpawnArgs):Promise<number>;

export function OpenSettingsWindow(arg1:main.OpenSettingsWindowArgs):Promise<void>;

export function OpenerOpenPath(arg1:main.OpenerOpenPathArgs):Promise<void>;

export function OpenerOpenURL(arg1:main.OpenerOpenURLArgs):Promise<void>;

export function OpenerRevealItem(arg1:main.OpenerOpenPathArgs):Promise<void>;

export function ProcessExit(arg1:main.ProcessExitArgs):Promise<void>;

export function ProcessRelaunch():Promise<void>;

export function PtyListShells():Promise<Array<string>>;

export function PtyShellName(arg1:number):Promise<string>;

export function SecretsDelete(arg1:main.SecretsDeleteArgs):Promise<void>;

export function SecretsGet(arg1:main.SecretsGetArgs):Promise<any>;

export function SecretsGetAll(arg1:main.SecretsGetAllArgs):Promise<Array<any>>;

export function SecretsSet(arg1:main.SecretsSetArgs):Promise<void>;

export function ShellBgKill(arg1:types.ShellBgKillArgs):Promise<void>;

export function ShellBgList():Promise<Array<shell.BgProcessInfo>>;

export function ShellBgLogs(arg1:types.ShellBgLogsArgs):Promise<string>;

export function ShellBgSpawn(arg1:types.ShellBgSpawnArgs):Promise<number>;

export function ShellRunCommand(arg1:types.ShellRunArgs):Promise<string>;

export function ShellSessionClose(arg1:main.ShellSessionCloseArgs):Promise<void>;

export function ShellSessionOpen(arg1:types.ShellSessionOpenArgs):Promise<number>;

export function ShellSessionRun(arg1:types.ShellSessionRunArgs):Promise<types.ShellSessionResult>;

export function StoreLoad(arg1:types.StoreLoadArgs):Promise<Record<string, any>>;

export function StoreSave(arg1:types.StoreSaveArgs):Promise<void>;

export function UpdaterCheck():Promise<Record<string, any>>;

export function WorkspaceAuthorize(arg1:main.WorkspaceAuthorizeArgs):Promise<void>;

export function WorkspaceCurrentDir():Promise<string>;

export function WorkspacePickDirectory():Promise<string>;

export function WslDefaultDistro():Promise<string>;

export function WslHome(arg1:main.WslHomeArgs):Promise<string>;

export function WslListDistros():Promise<Array<workspace.WSLDistro>>;
